model: "reg"
Classifier:
    vocab_size: 21
    model_type: "ResPreAct"
    n_layers: 9
    max_length: 512
    filters: [64, 64, 64, 128, 128, 128, 256, 256, 256]
    kernels: [9, 9, 9, 9, 9, 9, 9, 9, 9]
    dilations: [2, 2, 2, 2, 2, 2, 2, 2, 2]
    strides: [1, 2, 2, 1, 2, 2, 1, 1, 2]
    l1: 0.0
    l2: 0.0
    rate: 0.2
    use_attention: True
    attention_loc: 5
    use_global_pos: False
    temporal_encode: 21
    learning_rate: 0.0001
    batch_size: 256
    epochs: 40
    down_sample: 5 # needs to be the same as the number of 2s in strides
    norm: "Batch" # "Layer" "Batch" "Instance"
    file: "/ThermalGAN/weights/Classifier/OGT_IMG_DATA_2/model1_weights.h5"
    checkpoint_filepath: "/ThermalGAN/weights/Classifier/OGT_IMG_DATA_2/checkpoint"
    history: "/ThermalGAN/weights/Classifier/OGT_IMG_DATA_2/"
Data:
    max_length: 512
    max_samples: 4000000
    base_dir: '/ThermalGAN/data/records/OGT_IMG_2025_05_20'
    train_dir: 'train/*.tfrecord'
    val_dir: 'val/*.tfrecord'
    n_shards: 100 # How many shards to use
    shards: 100


